### ISSUE TITLE
Question: No Inventory Slots

### ISSUE THREAD

**Issue by VimaMT** [Valorless/HavenElytra#2]
I have just downloaded and tried out HavenElytra.

Looking at gui-main.yml, gui-separate.yml and gui-combine.yml, it appears that no inventory slots were created by default that would allow me to combine or separate elytras.

Should I be creating those, and do you have an example I can folow, please?

**Comment by VimaMT** [comment]
Please disregard this question. I found examples in the templates folder. Thanks for your attention.

**Comment by Valorless** [comment]
I'm glad you found what you were looking for ^^
Don't hesitate to open a new ticket any time, if you discover anything, or have any questions :)
