### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by krw1r** [Valorless/HavenElytra#3]
how do i merge the two, i open the gui and it doesnt let me do anything with it, the slots are just black, i have havenutils too

**Comment by Valorless** [comment]
Greetings!
Have you remembered to set up the gui, or used the templates provided?
The gui is by default blank, to avoid complications.

**Comment by krw1r** [comment]
smh, i just realised i had to set that up myself, thank you!! i just did it and it works perfectOn 21 Sep 2023, at 11:19 pm, Valor ***@***.***> wrote:﻿
Greetings!
Have you remembered to set up the gui, or used the templates provided?
The gui is by default blank, to avoid complications.

**Comment by Valorless** [comment]
I'm happy the issue is solved ^^

**Comment by bandarx34** [comment]
@Valorless how do you set up the ui

**Comment by Valorless** [comment]
> @Valorless how do you set up the ui
> 

Hi there ^^
You can either manually set up the gui inside the menu's respective .yml file, or use the templates provided in /plugins/HavenElytra/templates :)

**Comment by bandarx34** [comment]
where do i find that /plugins thing.. its not in config files.

**Comment by Valorless** [comment]
> where do i find that /plugins thing.. its not in config files. 
> 

Its not a config entry, it's the name of the folder you have all plugins in :)
