### ISSUE TITLE
Separating damaged havenelytra and then combining will lead to more durability

### ISSUE THREAD

**Issue by ghost** [Valorless/HavenElytra#4]
Separating damaged havenelytra and then combining will lead to more durability...............

**Comment by Valorless** [comment]
When I get around to it, I'll change so the items are required to be fully repaired in order to combine or separate :)

**Comment by ghost** [comment]
That's a perfect solution. Thank you.

**Comment by Valorless** [comment]
I'm happy to say I've updated the plugin to require fully repaired items.
I've added 2 needed functions as well.
[**Update Log**](https://www.spigotmc.org/resources/havenelytra-combined-chestplates-and-elytras.109583/update?update=538445)

I'll close the Issue, and if you need any more assistance, feel free to reopen it, or create a new issue ^^
Take care!

**Comment by ghost** [comment]
Thank you very much, but there is still the issue that if you decide to separate your already damaged combined elytra, you will end up with fully repaired chestplate and elytra that you can then combine once more to cheat yourself a fully repaired combined elytra. Any ideas how I can get around this except for disabling separating?

**Comment by ghost** [comment]
Maybe it is possible to make separating cost money/currency?

**Comment by Valorless** [comment]
> Thank you very much, but there is still the issue that if you decide to separate your already damaged combined elytra, you will end up with fully repaired chestplate and elytra that you can then combine once more to cheat yourself a fully repaired combined elytra. Any ideas how I can get around this except for disabling separating?

This was reported to me yesterday by a close friend, and I already think I know why.
I've been stressed lately, and the changed with durability I did for combining, was not added to separation.

I'll add so either the elytra needs to be fully repaired to be separated; or I'll transfer the durability onto the separated elytra.
I'll fix it when I have time :)

**Comment by Valorless** [comment]
> Maybe it is possible to make separating cost money/currency?

I can add optional Vault integration sure! :D

**Comment by Valorless** [comment]
I've fixed the durability issue and added Vault to make cost possible :)
You can find the update here: https://www.spigotmc.org/resources/havenelytra-combined-chestplates-and-elytras-1-18-1-20-4.109583/update?update=540240

I'll close the Issue, and if you need any more assistance, feel free to reopen it, or create a new issue ^^
Take care!
